### ISSUE TITLE
Rename chapter filename for intro tutorials

### ISSUE THREAD

**Issue by hx2A** [hx2A/py5book#57]
Can you rename the `tutorials/intro_to_py5_and_python_01.ipynb` file to `tutorials/intro_to_py5_and_python.ipynb`?

Here is what is in the _toc.yml file for the Tutorials:

```yml
- caption: Tutorials
  chapters:
  - file: tutorials/intro_to_py5_and_python
    sections:
    - glob: tutorials/intro_to_py5_and_python_*

  - file: tutorials/misc
    sections:
    - glob: tutorials/misc_*
```

The "chapter" needs to start with a file that must match `tutorials/intro_to_py5_and_python` exactly. The wildcard `*` is for the sections in the chapter, and the glob expression `tutorials/intro_to_py5_and_python_*` shouldn't also match with the notebook that starts the chapter.
